2019-12-04 15:20:56,751 DEBUG   MainThread:47878 [wandb_config.py:_load_defaults():110] no defaults not found in config-defaults.yaml
2019-12-04 15:20:56,754 DEBUG   MainThread:47878 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/ssd2/arthur/searchx-scaffolding, universal_newlines=False, shell=None, istream=None)
2019-12-04 15:20:56,771 DEBUG   MainThread:47878 [cmd.py:execute():722] Popen(['git', 'cat-file', '--batch-check'], cwd=/ssd2/arthur/searchx-scaffolding, universal_newlines=False, shell=None, istream=<valid stream>)
2019-12-04 15:20:56,780 DEBUG   MainThread:47878 [cmd.py:execute():722] Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/ssd2/arthur/searchx-scaffolding, universal_newlines=False, shell=None, istream=None)
2019-12-04 15:20:56,785 DEBUG   MainThread:47878 [cmd.py:execute():722] Popen(['git', 'status', '--porcelain', '--untracked-files'], cwd=/ssd2/arthur/searchx-scaffolding, universal_newlines=False, shell=None, istream=None)
2019-12-04 15:20:56,804 DEBUG   MainThread:47878 [run_manager.py:__init__():535] Initialized sync for searchx-scaffolding-src/o2j18tzc
2019-12-04 15:20:56,806 INFO    MainThread:47878 [run_manager.py:wrap_existing_process():1131] wrapping existing process 47731
2019-12-04 15:20:56,806 WARNING MainThread:47878 [io_wrap.py:register():104] SIGWINCH handler was not None: <Handlers.SIG_DFL: 0>
2019-12-04 15:20:56,810 DEBUG   MainThread:47878 [connectionpool.py:_new_conn():959] Starting new HTTPS connection (1): pypi.org:443
2019-12-04 15:20:56,862 DEBUG   MainThread:47878 [connectionpool.py:_make_request():437] https://pypi.org:443 "GET /pypi/wandb/json HTTP/1.1" 200 38231
2019-12-04 15:20:56,873 INFO    MainThread:47878 [run_manager.py:init_run():916] system metrics and metadata threads started
2019-12-04 15:20:56,873 INFO    MainThread:47878 [run_manager.py:wrap_existing_process():1148] informing user process we are ready to proceed
2019-12-04 15:20:56,874 INFO    MainThread:47878 [run_manager.py:_sync_etc():1255] entering loop for messages from user process
2019-12-04 15:20:57,764 INFO    Thread-3  :47878 [run_manager.py:_on_file_created():671] file/dir created: /ssd2/arthur/searchx-scaffolding/wandb/dryrun-20191204_142055-o2j18tzc/wandb-metadata.json
2019-12-04 15:21:52,933 INFO    MainThread:47878 [run_manager.py:_sync_etc():1278] received message from user process: {"exitcode": 1}
2019-12-04 15:21:52,933 INFO    MainThread:47878 [run_manager.py:_sync_etc():1364] closing log streams and sending exitcode to W&B
2019-12-04 15:21:52,933 INFO    MainThread:47878 [run_manager.py:shutdown():1055] shutting down system stats and metadata service
878 [o2j18tzc:run_manager.py:_sync_etc():1364] closing log streams and sending exitcode to W&B
2019-12-04 15:21:52,933 INFO    MainThread:47878 [o2j18tzc:run_manager.py:shutdown():1055] shutting down system stats and metadata service
